apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-square.fullname" . }}
  labels:
    {{- include "go-square.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "go-square.selectorLabels" . | nindent 4 }}
