apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "go-square.fullname" . }}
  labels:
    {{- include "go-square.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "go-square.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "go-square.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ printf "v%s" .Chart.AppVersion }}{{ default .Values.image.tag "" }}"
          ports:
            - containerPort: {{ .Values.service.port }}
