name: new-commit

on:
  push:
    branches:
      - main

jobs:
  patch-version-bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        

      - name: Bump the tag
        id: set_tag
        run: |
          new_version=`git describe --tags --abbrev=0 | awk -F. '{OFS="."; $NF+=1; print $0}'`
          echo "GIT_TAG=$(echo $new_version)" >> $GITHUB_ENV


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker buildx build -t nasakin/go-square:${{ env.GIT_TAG }} .
          docker push nasakin/go-square:${{ env.GIT_TAG }}
         

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Bump version in Helm Chart
        env: 
          GIT_TAG: ${{ env.GIT_TAG }}
        run: |
          pip install -r ./scripts/requirements.txt 
          python ./scripts/helm-chart-tags.py
      
      - name: Push to origin
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add .
          git tag -a ${{ env.GIT_TAG }} -m "Bump patch version"
          git push origin ${{ env.GIT_TAG }}
