name: new-commit

on:
  push:
    branches:
      - main
      - app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t nasakin/go-square:${{  github.ref_name }}" .
          docker push nasakin/go-square:${{  github.ref_name }}"

      - name: Create Git tag
        id: set_tag
        uses: anothrNick/github-tag-action@72cc9b65fd4cdd0de63b8dd7c098e1741ae0951a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
         

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Bump version in Helm Chart
        env: 
          GIT_TAG: ${{ steps.set_tag.outputs.tag }}
        run: python ./scripts/helm-chart-tags.py
